# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - HelloWorldeBiznes

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://ebiznes.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_acddc3e8fc56452abdc3498f178d64a8 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_ae8a0e1dfcf24ab7a4d66e233e5a6c7f }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ebiznes.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_acddc3e8fc56452abdc3498f178d64a8 }}/hello-word:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'HelloWorldeBiznes'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a86f1c28513244aa9a4bbabec9affe04 }}
        images: 'ebiznes.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_acddc3e8fc56452abdc3498f178d64a8 }}/hello-word:${{ github.sha }}'